// Dados das instituições cadastradas na planilha instituições.ods
// Os campos abaixo foram mantidos para permitir a exibição detalhada no mapa.
// lat/lng representam a localização do município informado no cadastro.

const localizacoes = [
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Associação Amigas do bem Curitiba",
    "responsavel": "Silvana Aparecida Serafim Campos",
    "cnpj": "50832448000140",
    "fundacao": "2023-05-02",
    "tempo_atuacao": "Desde 2019",
    "email": "amigasdobemcuritiba@gmail.com",
    "endereco": "Rua Manoel Ricardo de Oliveira 32 bairro novo A sítio cercado.",
    "mais_de_uma_sede": "",
    "telefone": "41998600978 ou 41997335455",
    "site": "Amigasdobemcuritiba.org",
    "redes_sociais": "Amigas do bem Curitiba",
    "tipo_entidade": "Associação |  Asociación",
    "areas_atuacao": "Migração e refúgio | Migración y refugio",
    "problema": "Atendemos migrantes e buscamos apoiar sua inserção no novo recomeço. Levá-los a sua emancipação financeira e sua integração na sociedade.",
    "como_resolve": "Oferecemos inicialmente ajuda com cesta básica e quando possível utilidades para a casa em seguida orientamos onde buscar por seus documentos, encaminhar para CRAS e rede de saúde. Orientar e encaminhar para vagas de trabalho. Também ofertamos oficinas de beleza e culinária para mulheres, rodas de conversas e palestras com profissionais na área da psicologia, apoio básico jurídico voluntario.",
    "atividades": "Entrega de alimentos, roupas, cobertores Palestras , oficinas de beleza e culinária. Festa em datas especiais como:natal, páscoa, dia das crianças. Captação de doações de objetos de casa e entrega dos mesmos. Divulgação nos grupos de watts e redes sociais de vagas de trabalho recebidas de parceiros da associação. Todas informações relevantes que possam ajudar as famílias migrantes atendidas e também em nossa comunidade colaborar com nossas atividades abertas a todos sejam migrantes ou não.",
    "publico_principal": "Famílias de migrantes venezolanos e cubanos.",
    "segundo_publico": "Também brasileiros nossa comunidade que sentira necessidades de participar das atividades da associação. Abertos a comunidade onde estamos .",
    "outros_publicos": "",
    "nacionalidades": "Venezuelanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Encaminhamento para políticas públicas | Direccionamiento a políticas públicas",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "De segunda feira a sexta-feira das 9:00 as 17:00",
    "categorias": [
      "Migração e refúgio | Migración y refugio"
    ],
    "nacionalidades_lista": [
      "Venezuelanos"
    ]
  },
  {
    "city": "Toledo",
    "lat": -24.7246,
    "lng": -53.7413,
    "org": "Cáritas Diocesana de Toledo",
    "responsavel": "Marcus Vinicius de Jesus Sanita",
    "cnpj": "49.528.239/0001-28",
    "fundacao": "1968-10-25",
    "tempo_atuacao": "58",
    "email": "caritasdiocesanadetoledo@gmail.com",
    "endereco": "Rua General Rondon, 2006, Jardim La Salle, Toledo-PR, CEP 85902-090",
    "mais_de_uma_sede": "",
    "telefone": "(45) 99830-0493",
    "site": "https://www.instagram.com/caritastoledopr/",
    "redes_sociais": "@caritastoledopr",
    "tipo_entidade": "OSC | ONG, Igreja | Iglesia",
    "areas_atuacao": "Migração e refúgio | Migración y refugio",
    "problema": "Documentação de Migrantes",
    "como_resolve": "Montando a pasta de documentos necessários para o migrante levar até a Polícia Federal",
    "atividades": "Ajuda com a Documentação de Migrantes; Encaminhamento para trabalho; Escola de Língua Portuguesa para Migrantes.",
    "publico_principal": "Migrantes",
    "segundo_publico": "Migrantes",
    "outros_publicos": "No momento não",
    "nacionalidades": "Todos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Regularização migratória - documentação | Regularización migratoria - documentación",
    "forma_acesso": "Agendamento | Con cita agendada",
    "horarios": "Segunda-feira a Sexta-feira, das 08h às 12h e das 13h30 às 17h",
    "categorias": [
      "Migração e refúgio | Migración y refugio"
    ],
    "nacionalidades_lista": [
      "Todos"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Instituto Semear",
    "responsavel": "Jeferson Leite Leal",
    "cnpj": "63461060000121",
    "fundacao": "2025-09-02",
    "tempo_atuacao": "5 anos",
    "email": "jefersonleal@msn.com",
    "endereco": "RUA ANTÔNIO REBELATTO 1455 - SOB 01",
    "mais_de_uma_sede": "",
    "telefone": "53999660740",
    "site": "https://institutosemearsocial.org.br/",
    "redes_sociais": "https://www.instagram.com/institutosemear.socialbr?igsh=MTU0eXJycnZ6NGFybw==",
    "tipo_entidade": "Instituto | Instituto",
    "areas_atuacao": "Migração e refúgio | Migración y refugio",
    "problema": "O Instituto Semear busca acolher e apoiar imigrantes que chegam à comunidade em situação de vulnerabilidade social e econômica, enfrentando dificuldades de adaptação, falta de recursos básicos, acesso a serviços e integração social.",
    "como_resolve": "O Instituto Semear atua por meio da mobilização da comunidade, buscando apoio, doações, parcerias e voluntários para atender às necessidades dos imigrantes, promovendo acolhimento, orientação e auxílio no processo de integração à comunidade.",
    "atividades": "O Instituto Semear realiza o acolhimento e a orientação de imigrantes; promove campanhas para arrecadação e distribuição de alimentos, roupas e outros itens de necessidade básica; mobiliza a comunidade e parceiros para obtenção de doações; auxilia no encaminhamento aos serviços públicos e instituições competentes; e oferece apoio no processo de adaptação e integração social.",
    "publico_principal": "Imigrantes em situação de vulnerabilidade social e econômica acolhidos pelo Instituto Semear.",
    "segundo_publico": "Famílias de imigrantes, especialmente aquelas que chegam à comunidade enfrentando dificuldades financeiras, sociais e de adaptação.",
    "outros_publicos": "Sim. Crianças, adolescentes, mulheres e demais pessoas em situação de vulnerabilidade pertencentes às famílias imigrantes acolhidas e acompanhadas pelo Instituto Semear.",
    "nacionalidades": "Venezuelanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Regularização migratória - documentação | Regularización migratoria - documentación",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "De segunda ao domingo das 9hs até 21hs.",
    "categorias": [
      "Migração e refúgio | Migración y refugio"
    ],
    "nacionalidades_lista": [
      "Venezuelanos"
    ]
  },
  {
    "city": "Colombo",
    "lat": -25.2925,
    "lng": -49.2263,
    "org": "Veneza Unidos con Alegría",
    "responsavel": "Angel Keneth López Farfán",
    "cnpj": "Ainda não tem",
    "fundacao": "2024-09-20",
    "tempo_atuacao": "3 años",
    "email": "graphictopdigitalpr@gmail.com",
    "endereco": "Rua Cerro Azul 397 Paloma Colombo",
    "mais_de_uma_sede": "2026-08-12",
    "telefone": "41988756544",
    "site": "Veneza Unidos con Alegría",
    "redes_sociais": "Veneza Unidos con Alegría",
    "tipo_entidade": "Associação |  Asociación",
    "areas_atuacao": "Empreendedorismo | Emprendimiento",
    "problema": "Dar a conocer los emprendimientos",
    "como_resolve": "Realizando férias de Emprendedores",
    "atividades": "Ferias de Emprendedores, Actividades sociales y recreativas con los emprendedores",
    "publico_principal": "Público Migrante",
    "segundo_publico": "Público local",
    "outros_publicos": "No",
    "nacionalidades": "Venezuelanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Emprendedores",
    "forma_acesso": "Atendimento Externo | Atendimiento Externo",
    "horarios": "Horario de oficina",
    "categorias": [
      "Empreendedorismo | Emprendimiento"
    ],
    "nacionalidades_lista": [
      "Venezuelanos"
    ]
  },
  {
    "city": "Almirante Tamandaré",
    "lat": -25.3247,
    "lng": -49.31,
    "org": "Instituto Boneca Feliz",
    "responsavel": "Hamilton Ferreira da Silva",
    "cnpj": "Em processo de registro",
    "fundacao": "2026-02-14",
    "tempo_atuacao": "4 anos",
    "email": "instituto.boneca.feliz@gmail.com",
    "endereco": "Av. Rafaela, 23 - Restinga Seca - Almirante Tamandaré/PR CEP: 83512-030",
    "mais_de_uma_sede": "2026-08-12",
    "telefone": "(31) 99957-9052",
    "site": "Não possui",
    "redes_sociais": "Não Possui",
    "tipo_entidade": "OSC | ONG, OSC em processod e Registro",
    "areas_atuacao": "Encaminhamento a Organizações e Setores de Assistência a Migrantes",
    "problema": "Orientação de Direitos dos Migrantes e Assistência",
    "como_resolve": "Faz a ponte entre a demanda detectada e quem pode dar solução",
    "atividades": "Orientação através de palestras em Escolas contra o abuso e exploração sexual infantojuvenil",
    "publico_principal": "Pessoas em geral",
    "segundo_publico": "Assitência com doação de cestas básicas, roupas e outros ítens",
    "outros_publicos": "Público em geral",
    "nacionalidades": "Haitianos, Venezuelanos, Cubanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Encaminhamento para políticas públicas | Direccionamiento a políticas públicas",
    "forma_acesso": "Atendimento Externo | Atendimiento Externo",
    "horarios": "Segunda a sexta-feira",
    "categorias": [
      "Encaminhamento a Organizações e Setores de Assistência a Migrantes"
    ],
    "nacionalidades_lista": [
      "Haitianos",
      "Venezuelanos",
      "Cubanos"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Missão Gênesis",
    "responsavel": "Renata Caroline de Souza",
    "cnpj": "43.973.623/0001-53",
    "fundacao": "2021-09-14",
    "tempo_atuacao": "6 anos",
    "email": "missaogenesisoficial@gmail.com",
    "endereco": "Rua São Francisco 126",
    "mais_de_uma_sede": "",
    "telefone": "+55 (41) 99822-2243",
    "site": "Não temos",
    "redes_sociais": "@missaogenesisoficial",
    "tipo_entidade": "Igreja | Iglesia",
    "areas_atuacao": "Desenvolvimento de projetos sociais",
    "problema": "A Missão Gênesis busca promover a justiça social e contribuir para a redução das desigualdades.",
    "como_resolve": "Realizamos esse propósito por meio de ações sociais voltadas ao atendimento de pessoas e famílias em situação de vulnerabilidade. Entre nossas iniciativas, estão a distribuição de cestas básicas, atividades com crianças, incluindo reforço escolar e acompanhamento, além do atendimento à população em situação de rua. Para aqueles que desejam reconstruir suas vidas e sair da situação de rua, oferecemos encaminhamento para clínicas de reabilitação, realizando o acompanhamento durante esse processo. Também contamos com uma casa de acolhimento, que oferece suporte e um ambiente de cuidado para pessoas que necessitam desse atendimento e contribuindo para sua reinserção social e para a construção de novas perspectivas de vida.",
    "atividades": "As principais atividades que realizamos estão voltadas ao atendimento e acolhimento de pessoas em situação de rua, oferecendo, orientação e suporte de acordo com as necessidades de cada indivíduo. Também desenvolvemos ações de apoio a famílias em situação de vulnerabilidade, atividades socioeducativas com crianças, incluindo reforço escolar, distribuição de cestas básicas e encaminhamento para clínicas de reabilitação, com acompanhamento durante esse processo.",
    "publico_principal": "Nosso principal público é composto por pessoas e famílias em situação de vulnerabilidade social. A partir do momento em que procuram nossa instituição, buscamos compreender suas necessidades e oferecer, dentro de nossas possibilidades, o apoio e o encaminhamento necessários, contribuindo para a melhoria de sua qualidade de vida e para a superação das situações de vulnerabilidade.",
    "segundo_publico": "Após a população em situação de rua, nosso segundo principal público atendido é composto por famílias em situação de vulnerabilidade social",
    "outros_publicos": "Sim. Além dos principais públicos atendidos, também prestamos assistência a outros grupos em situação de vulnerabilidade. Entre eles, estão famílias provenientes de outros estados, às quais oferecemos apoio e, quando necessário, auxílio para o retorno à sua cidade de origem. Também já realizamos o atendimento e acolhimento de imigrantes de diferentes países, oferecendo suporte de acordo com suas necessidades e buscando contribuir para sua adaptação, segurança e integração social.",
    "nacionalidades": "Brasileiros, Venezuelanos, Haitianos, Peruanos e Argentinos.",
    "perfil_migratorio": "Migrantes Internacionais, Solicitantes de refugiu e população brasileira em vulnerabilidade.",
    "servicos": "Acolhimento, empregabilidade e encaminhamento para políticas públicas.",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "Segunda a Sábado em horário comercial e Domingo das 09h a 13h",
    "categorias": [
      "Desenvolvimento de projetos sociais"
    ],
    "nacionalidades_lista": [
      "Brasileiros",
      "Venezuelanos",
      "Haitianos",
      "Peruanos",
      "Argentinos"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Recanto Esperança",
    "responsavel": "Cláudia",
    "cnpj": "07394310000187",
    "fundacao": "2004-12-09",
    "tempo_atuacao": "22 anos",
    "email": "contato@recantoesperanca.org.br",
    "endereco": "Rua Laércio Nakashima, 110 Uberaba Curitiba PR CEP81550572",
    "mais_de_uma_sede": "",
    "telefone": "41 98518-8700",
    "site": "www.recantoesperanca.org.br",
    "redes_sociais": "Instagram @esperanca.recantoFacebook https://pt-br.facebook.com/recantoesperancaOng/ Linkedin https://br.linkedin.com/company/recantoesperancaYoutube https://youtube.com/@recantoesperanca",
    "tipo_entidade": "OSC | ONG, Associação |  Asociación",
    "areas_atuacao": "Assistência social | Asistencia social",
    "problema": "Ciclo contínuo de vulnerabilidades sociais como violência doméstica, gravidez na adolescência, baixa valorização da educação e o subemprego provenientes da disfunção familiar, que afetam negativamente o desenvolvimento das crianças e perpetuam situações de desigualdade e exclusão.",
    "como_resolve": "Abordagem integrada que combina educação, desenvolvimento socioemocional, engajamento familiar e suporte estrutural para romper o ciclo de vulnerabilidades sociais e promover inclusão e autonomia.",
    "atividades": "Serviço de convivência e fortalecimento de vínculos para crianças e adolescentes entre 6 e 17 anosOficinas de floorball para crianças, adolescente e adultos",
    "publico_principal": "crianças e adolescentes entre 6 e 17 anos",
    "segundo_publico": "as famílias das crianças e adolescentes atendidos",
    "outros_publicos": "",
    "nacionalidades": "Uma criança venezuelana",
    "perfil_migratorio": "População brasileira em vulnerabilidade | Población brasileña en situación de vulnerabilidad",
    "servicos": "Educação | Educación",
    "forma_acesso": "Lista de espera  | Lista de espera",
    "horarios": "Segunda a sexta das 8h30 às 11h e das 13h30 às 16h",
    "categorias": [
      "Assistência social | Asistencia social"
    ],
    "nacionalidades_lista": [
      "Uma criança venezuelana"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Associação de Capoeira Navalha de Prata Megê",
    "responsavel": "Robson Jaime Pereira",
    "cnpj": "64.462.022/0001-56",
    "fundacao": "2025-11-26",
    "tempo_atuacao": "16 anos",
    "email": "gruponavalhadeprata@gmail.com",
    "endereco": "rua da pedreira, 614",
    "mais_de_uma_sede": "",
    "telefone": "41985086381",
    "site": "nao possuimos ainda",
    "redes_sociais": "https://www.instagram.com/navalhadeprata1?igsh=bGZ4MW5iN3pjenRo ,https://youtube.com/@navalhadepratadino5728?si=NFFPwuQuRSOloWWy , https://www.facebook.com/share/1H4mjuKJwz/ , https://www.facebook.com/share/185j2KjBbn/ ,                   https://www.tiktok.com/@dino131304?_r=1&_t=ZS-94WKuIhmAj9",
    "tipo_entidade": "Associação |  Asociación",
    "areas_atuacao": "Esporte, Cultura, Lazer",
    "problema": "A ACNPM atua para combater o apagamento histórico, a invisibilidade e o racismo estrutural/institucional que afetam populações vulneráveis, em especial migrantes, refugiados, afrodescendentes e jovens periféricos. Respondemos à carência de espaços de acolhimento e integração sociocultural, enfrentando os impactos psicossociais da exclusão, a barreira do pertencimento e a falta de oportunidades de protagonismo social e cidadania.",
    "como_resolve": "Resolvemos este problema utilizando a capoeira e a cultura afro-brasileira como tecnologia social, de saúde mental e de letramento racial. Promovemos a integração intercultural e o acolhimento comunitário por meio do conceito de \"Quilombo Moderno\" — um território educativo e afetivo que alia a salvaguarda do patrimônio imaterial à Engenharia Ancestral (STEM), garantindo inclusão radical, acessibilidade plena, fortalecimento da identidade e autonomia socioemocional.",
    "atividades": "Oficinas de Capoeira e Musicalidade Tradicional: Aulas de movimentação, toques de berimbau/percussão e vivências corporais adaptadas para crianças, jovens,  e migrantes.Rodas de Conversa e Letramento Racial: Dinâmicas dialógicas focadas em ancestralidade, direitos humanos, saúde mental e combate ao racismo e à xenofobia.Capacitação e Protagonismo Juvenil: Formação de multiplicadores e agentes culturais comunitários para liderança e gestão cultural.",
    "publico_principal": "crianças 06 anos a 13 anos",
    "segundo_publico": "adolescentes 14 a 18 anos",
    "outros_publicos": "jovens a partir de 19 anos",
    "nacionalidades": "Haitianos",
    "perfil_migratorio": "Refugiados | Refugiados",
    "servicos": "Mediação cultural | Mediación cultural",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "a partir das 10h",
    "categorias": [
      "Esporte",
      "Cultura",
      "Lazer"
    ],
    "nacionalidades_lista": [
      "Haitianos"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Associação Beneficente Projeto Nova Terra",
    "responsavel": "Andréia Ribas",
    "cnpj": "18.317.402.0001-80",
    "fundacao": "2010-02-25",
    "tempo_atuacao": "16 anos",
    "email": "secretariaongnovaterra@hotmail.com",
    "endereco": "Rua Enemézio do Rosário Junior, 350Ponto de referência: ONG NOVA TERRA",
    "mais_de_uma_sede": "",
    "telefone": "(41)98455-6490 Adriano Ribas Presidente",
    "site": "www.ongnovaterra.com",
    "redes_sociais": "Projeto Nova Terra",
    "tipo_entidade": "OSC | ONG",
    "areas_atuacao": "Assistência social | Asistencia social",
    "problema": "A Associação Beneficente Projeto Nova Terra busca enfrentar as dificuldades de inclusão e integração vivenciadas por imigrantes, especialmente venezuelanos, que chegam à comunidade e encontram barreiras para participar plenamente da vida social, cultural e comunitária. Entre esses desafios estão a adaptação a uma nova realidade, a dificuldade de criar vínculos, o acesso limitado a oportunidades e a necessidade de fortalecer a convivência entre imigrantes e a população local. A organização existe para contribuir com uma comunidade mais acolhedora, inclusiva e aberta à diversidade cultural.",
    "como_resolve": "A Associação Beneficente Projeto Nova Terra promove ações que aproximam imigrantes, especialmente venezuelanos, da comunidade local, criando espaços de convivência, participação e desenvolvimento. Por meio de atividades culturais, educativas, oficinas, projetos sociais e ações comunitárias, a organização favorece a troca de experiências, o fortalecimento de vínculos e a valorização das diferentes culturas. A proposta é proporcionar aos imigrantes oportunidades de participação, expressão e integração, ao mesmo tempo em que sensibiliza a comunidade para o respeito à diversidade e à convivência intercultural.",
    "atividades": "A organização desenvolve atividades sociais, educativas e culturais voltadas à integração e ao desenvolvimento da comunidade. Entre as principais ações estão oficinas para crianças, adolescentes e famílias, atividades de musicalização, música, dança, teatro, cultura popular e outras expressões artísticas, além de ações de convivência e formação. No trabalho com imigrantes, busca utilizar essas atividades como ferramentas de aproximação, permitindo que venezuelanos e pessoas de outras nacionalidades participem da vida comunitária, compartilhem sua cultura, desenvolvam vínculos e encontrem novas oportunidades de integração social.",
    "publico_principal": "O público principal atendido pela Associação Beneficente Projeto Nova Terra é formado por crianças, adolescentes, famílias e moradores da comunidade de Atuba, especialmente pessoas em situação de vulnerabilidade social. Dentro dessa atuação, a organização também promove a inclusão e integração de imigrantes, especialmente venezuelanos que vivem na região, criando oportunidades de convivência, participação e troca cultural. Dessa forma, o trabalho fortalece a comunidade local e contribui para que imigrantes sejam acolhidos e possam participar ativamente da vida comunitária.",
    "segundo_publico": "O segundo principal público atendido pela Associação Beneficente Projeto Nova Terra é formado por imigrantes residentes na região de Atuba, especialmente venezuelanos e suas famílias. A organização busca promover sua inclusão e integração à comunidade por meio de atividades sociais, culturais e educativas, criando espaços de convivência, troca de experiências e valorização da diversidade cultural.",
    "outros_publicos": "não",
    "nacionalidades": "Brasileiros e Venezuelanos",
    "perfil_migratorio": "População Brasileira em vulnerabilidade e refugiados",
    "servicos": "Acolhimento e Educação",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "segunda a sexta feria das 8h as 18h da tarde.",
    "categorias": [
      "Assistência social | Asistencia social"
    ],
    "nacionalidades_lista": [
      "Brasileiros",
      "Venezuelanos"
    ]
  },
  {
    "city": "Fazenda Rio Grande",
    "lat": -25.6624,
    "lng": -49.3073,
    "org": "INSTITUTO CULTURAL E FOLCLORICO ALMA TRICOLOR",
    "responsavel": "Francisco Javier Rodriguez Tayupo",
    "cnpj": "68.493.739/0001-16",
    "fundacao": "2026-07-17",
    "tempo_atuacao": "4",
    "email": "almatricolorcwb@gmail.com",
    "endereco": "Rua Bigua n° 1337- CEP: 83824-466. Bairro Gralha Azul- Fazenda Rio Grande, PR",
    "mais_de_uma_sede": "",
    "telefone": "41-98757 1082",
    "site": "",
    "redes_sociais": "@almatricolorcwb",
    "tipo_entidade": "Instituto | Instituto",
    "areas_atuacao": "Migração e refúgio, Assistência social, Direitos humanos, Educação e Empreendedorismo",
    "problema": "segregação cultural",
    "como_resolve": "promover a defensa e luta social dos migrante atraves das artes, a cultura e o folclore",
    "atividades": "apresentação de performance com foco social",
    "publico_principal": "Crianças e adolecentes migrantes",
    "segundo_publico": "adultos e idosos migrantes",
    "outros_publicos": "publico general brasileiro",
    "nacionalidades": "Venezuelanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Mediação cultural | Mediación cultural",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "Sabados 14h a 18h",
    "categorias": [
      "Migração e refúgio",
      "Assistência social",
      "Direitos humanos",
      "Educação e Empreendedorismo"
    ],
    "nacionalidades_lista": [
      "Venezuelanos"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "INSTITUTO ABUNA",
    "responsavel": "JOSÉ PRADO",
    "cnpj": "29615177000184",
    "fundacao": "2017-06-17",
    "tempo_atuacao": "INFORMALMENTE 13 ANOS, FORMALMENTE 9 ANOS",
    "email": "CONTATO@ABUNA.ORG.BR",
    "endereco": "AV MAL FLORIANO PEIXOTO, 2590 - PAROLIN, CURITIBA, CEP 80.220-001",
    "mais_de_uma_sede": "",
    "telefone": "41-3010-7451",
    "site": "ABUNA.ORG.BR",
    "redes_sociais": "INSTAGRAM E FACEBOOK - @ABUNABR",
    "tipo_entidade": "Instituto | Instituto",
    "areas_atuacao": "Migração e refúgio | Migración y refugio",
    "problema": "Existimos para que refugiados e migrantes em vulnerabilidade encontrem acolhimento, reconstruam suas vidas e possam novamente pertencer e participar.",
    "como_resolve": "Acolhemos e acompanhamos refugiados e migrantes na reconstrução de suas vidas. Criamos caminhos de pertencimento, autonomia e participação e construímos pontes entre pessoas e culturas.",
    "atividades": "Realizamos acolhimento humanitário e acompanhamento de pessoas e famílias migrantes e refugiadas em situação de vulnerabilidade. Oferecemos orientação e apoio nos processos de documentação e regularização migratória, acesso a serviços públicos, moradia, educação, saúde, aprendizagem da língua portuguesa e inserção no trabalho. Promovemos também ações de integração comunitária e cultural, fortalecimento da autonomia e construção de vínculos, articulando redes de voluntários, organizações parceiras e comunidades locais. Desenvolvemos ainda iniciativas de reassentamento e proteção humanitária e ações de articulação e incidência em temas relacionados à migração e ao refúgio.",
    "publico_principal": "Pessoas refugiadas em situação de vulnerabilidade, individualmente ou em família.",
    "segundo_publico": "Pessoas migrantes em situação de vulnerabilidade, individualmente ou em família.",
    "outros_publicos": "",
    "nacionalidades": "pessoas que falam árabe",
    "perfil_migratorio": "migrantes internacionais, refugiados, solicitantes de refúgio, apátridas",
    "servicos": "Acolhimento | Alojamiento temporal",
    "forma_acesso": "Atendimento Remoto | Atendimiento Online",
    "horarios": "horário comercial, dias úteis",
    "categorias": [
      "Migração e refúgio | Migración y refugio"
    ],
    "nacionalidades_lista": [
      "pessoas que falam árabe"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Associação de Peruanos Residentes No Estado Do Parana- Associação Contigo Perú",
    "responsavel": "Edita jenniffer Garcia Burga",
    "cnpj": "56.005.482/00012717",
    "fundacao": "2024-05-17",
    "tempo_atuacao": "2 anos e 3 meses",
    "email": "Associacaocontigoperuparana@gmail.com",
    "endereco": "Rua evaristo da veiga  2016,boqueirão Curitiba Parana",
    "mais_de_uma_sede": "",
    "telefone": "41996478232",
    "site": "Não  temos",
    "redes_sociais": "Associacaocontigoperuparana Facebook Associação Contigo Perú",
    "tipo_entidade": "Associação |  Asociación",
    "areas_atuacao": "Assistência social | Asistencia social",
    "problema": "A ASSOCIAÇÃO Contigo Perú  existe ,por vários  motivos,culturalmente manter viva  a cultura pra nossos legados futuros,receber futuros imigrantes peruanos,auxiliar na vida de cada ,un pós acreditamos que juntos somos mas fortes",
    "como_resolve": "Estamos contando con dos parceiros, como estamos limitados por ter un local contamos con. A  Provopar  Estadual,que nos auxiliar con cestas básicas, roupa, também  trabalhamos con o Ceasa(banco de Alimentos)e o Sesc de água verde que nos auxilia ,con material escolar ,roupa e brinquedos",
    "atividades": "Entregas de cestas básicas entrega de frutas e verduras ,eventos do dia das mães palestras do câncer, palestras da agressão  a mulher e doação de roupas",
    "publico_principal": "Pessoas diabéticas oncológica, crianças e de 35 a 80 anos",
    "segundo_publico": "Oncologicos, diabéticos,autistas etc",
    "outros_publicos": "Cegos,mancos,e problemas psicológicos",
    "nacionalidades": "En geral cubanos  venezolanos,argentinos,colombianos e peruanos brasileiros",
    "perfil_migratorio": "Imigrantes ,migrantes ,refugiados, e brasileiros ĺ",
    "servicos": "Entrega de cestas  basicas e banco de alimentos comida boa,encaminhado pra agências do imigrantes",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "São variadas",
    "categorias": [
      "Assistência social | Asistencia social"
    ],
    "nacionalidades_lista": [
      "En geral cubanos  venezolanos",
      "argentinos",
      "colombianos",
      "peruanos brasileiros"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Instituto Semear",
    "responsavel": "Jeferson Leite Leal",
    "cnpj": "63461060000121",
    "fundacao": "2025-09-02",
    "tempo_atuacao": "5",
    "email": "jefersonleal@msn.com",
    "endereco": "Antonio Rebelatto1455 Boqueirão - Curitiba PR",
    "mais_de_uma_sede": "2025-01-01",
    "telefone": "53999660740",
    "site": "https://institutosemearsocial.org.br",
    "redes_sociais": "https://www.instagram.com/institutosemear.socialbr?igsh=MTU0eXJycnZ6NGFybw==",
    "tipo_entidade": "Instituto | Instituto",
    "areas_atuacao": "Assistência social | Asistencia social",
    "problema": "Melhor atendimento do imigrante que chegam em Curitiba e Campo Magro.",
    "como_resolve": "Buscando a melhor solução.",
    "atividades": "Auxilio na construção de casa, acolhimento, ajuda nos documentos, trabalhos com crianças,  alimentação, dentre tantas outras atividades realizadas.",
    "publico_principal": "Imigrantes da Venezuela e haitiano.",
    "segundo_publico": "0",
    "outros_publicos": "Somente os imigrantes.",
    "nacionalidades": "Haitianos, Venezuelanos e cubanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Regularização migratória - documentação | Regularización migratoria - documentación",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "Todos os dias.",
    "categorias": [
      "Assistência social | Asistencia social"
    ],
    "nacionalidades_lista": [
      "Haitianos",
      "Venezuelanos",
      "cubanos"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Associação dos Estudantes Guineenses em Curitiba",
    "responsavel": "BRAIMA SEIDI",
    "cnpj": "26364467000104",
    "fundacao": "2016-06-26",
    "tempo_atuacao": "12 anos",
    "email": "curitibaguineense@gmail.com",
    "endereco": "Cep: 802.300.90 - Centro , Rua Alferes Poli 271",
    "mais_de_uma_sede": "",
    "telefone": "41998272054",
    "site": "não temos",
    "redes_sociais": "Insta: Associação dos Guineenses em Curitiba - AGC",
    "tipo_entidade": "Associação |  Asociación",
    "areas_atuacao": "Assistência social | Asistencia social",
    "problema": "Integrar os membros na comunidade, auxiliar na instalação de na resolução de questões relacionadas a documentação.",
    "como_resolve": "Por meio de dialogo e orientações.",
    "atividades": "Rodas de conversa, atividades desportivas para integrar a comunidade.",
    "publico_principal": "Migrantes Guineenses em termos gerais.",
    "segundo_publico": "Os filhos dos guineenses nascidos no Brasil",
    "outros_publicos": "Não",
    "nacionalidades": "Guineenses",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Acolhimento | Alojamiento temporal",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "Não temos horario especifico, depende de cada demanda.",
    "categorias": [
      "Assistência social | Asistencia social"
    ],
    "nacionalidades_lista": [
      "Guineenses"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Instituto Espaço Nova Vida",
    "responsavel": "Sandra Mara Assolari Nanemann",
    "cnpj": "10519060/0001-79",
    "fundacao": "2008-11-28",
    "tempo_atuacao": "4 anos",
    "email": "Institutoespaconv@hotmail.com",
    "endereco": "Rua Diogo Mugiatti,785  - Boqueirão Curitiba. PR",
    "mais_de_uma_sede": "",
    "telefone": "41 991519553",
    "site": "Não temos",
    "redes_sociais": "https://www.instagram.com/instituto.espaconovavida?stkn=NXB3MXlmN3MwYXdl",
    "tipo_entidade": "OSC | ONG",
    "areas_atuacao": "Educação e esportes",
    "problema": "Empregabilidade, a integração social de migrantes , fortalecimento da comunicação, autonomia, convivência comunitária e sentimento de pertencimento.",
    "como_resolve": "Aulas de Língua Portuguesa para migrantes e jiu-jítsu.",
    "atividades": "Aulas de Língua Portuguesa para migrantes e jiu-jítsu. Rodas de conversas para mulheres e migrantes.",
    "publico_principal": "Migrantes",
    "segundo_publico": "Crianças",
    "outros_publicos": "Mulheres",
    "nacionalidades": "Venezuelanos",
    "perfil_migratorio": "Migrantes internacionais | Migrantes internacionales",
    "servicos": "Ensino de língua portuguesa | Enseñanza de portugués",
    "forma_acesso": "Atendimento Remoto | Atendimiento Online",
    "horarios": "Sábados, 10h",
    "categorias": [
      "Educação e esportes"
    ],
    "nacionalidades_lista": [
      "Venezuelanos"
    ]
  },
  {
    "city": "Ponta Grossa",
    "lat": -25.095,
    "lng": -50.1619,
    "org": "CÁRITAS DIOCESANA DE PONTA GROSSA",
    "responsavel": "ERICA FRANCINE PILARSKI CLARINDO",
    "cnpj": "09.013.770/00001-43",
    "fundacao": "2007-08-05",
    "tempo_atuacao": "19 ANOS",
    "email": "administrativo@caritaspontagrossa.org.br",
    "endereco": "RUA SALVADOR DE MENDONÇA, 565 NOVA RUSSIA CEP 84053-040 PONTA GROSSA PARANÁ",
    "mais_de_uma_sede": "",
    "telefone": "42 32261165 / 42 98873-8266",
    "site": "www.caritasbrasileira.org.br",
    "redes_sociais": "@caritaspontagrossa",
    "tipo_entidade": "OSC | ONG",
    "areas_atuacao": "somos OSC de assistência social, garantia e defesa de direitos então trabalhamos com migração, dieritos humanos, empregabilidade, apoio psicossocial, capacitação profissional, empreendedorismo",
    "problema": "acesso  direitos",
    "como_resolve": "através das orientações, encaminhamentos",
    "atividades": "assessoria",
    "publico_principal": "Migrantes, refugiados e solicitantes de refugio",
    "segundo_publico": "brasileiros",
    "outros_publicos": "",
    "nacionalidades": "todos os citados",
    "perfil_migratorio": "ainda nao atendemos apatridas  os demais da lista todos",
    "servicos": "todos  da lista",
    "forma_acesso": "todos os  da lista mas  principalmente por agendamento",
    "horarios": "08:00 as 12:00 e das 13:00 as 17:00 de segunda a quinta",
    "categorias": [
      "somos OSC de assistência social",
      "garantia e defesa de direitos então trabalhamos com migração",
      "dieritos humanos",
      "empregabilidade",
      "apoio psicossocial",
      "capacitação profissional",
      "empreendedorismo"
    ],
    "nacionalidades_lista": [
      "Todos"
    ]
  },
  {
    "city": "Foz do Iguaçu",
    "lat": -25.5469,
    "lng": -54.5882,
    "org": "A Associação des Jeunes Haïtiens en Sciences de la Santé (AJHASS)",
    "responsavel": "Yonel Estavien",
    "cnpj": "44.748.906/0001-64",
    "fundacao": "2020-07-19",
    "tempo_atuacao": "6",
    "email": "ajhass.org@gmail.com",
    "endereco": "Rua Manoel Bandeira, 318, Vila Brasilia< Foz do Iguaçu, PR",
    "mais_de_uma_sede": "",
    "telefone": "45 9820-7532",
    "site": "www.ajhass.org",
    "redes_sociais": "Intagram: @AJHASS.ESV       Facebook: AJHASS,    TIKTOK AJHASS584",
    "tipo_entidade": "Associação |  Asociación",
    "areas_atuacao": "Saúde, Apoio psicossocial , Capacitação profissional",
    "problema": "Acesso a saúde para migrantes, refugiados e apátridas",
    "como_resolve": "A AJHASS – Associação dos Jovens Haitianos em Ciência da Saúde atua na promoção da saúde, inclusão social e garantia de direitos de migrantes, refugiados e apátridas. Desenvolve ações de educação em saúde, feira de atendimento em saúde, atendimento psicossocial, mediação intercultural, apoio ao acesso ao SUS, promoção da saúde mental, enfrentamento ao racismo e à xenofobia, capacitação de profissionais e atividades comunitárias, fortalecendo a integração e o acesso equitativo aos serviços de saúde e à rede de proteção social.",
    "atividades": "A AJHASS – Associação dos Jovens Haitianos em Ciência da Saúde atua na promoção da saúde, inclusão social e garantia de direitos de migrantes, refugiados e apátridas. Desenvolve ações de educação em saúde, feira de atendimento em saúde, atendimento psicossocial, mediação intercultural, apoio ao acesso ao SUS, promoção da saúde mental, enfrentamento ao racismo e à xenofobia, capacitação de profissionais e atividades comunitárias, fortalecendo a integração e o acesso equitativo aos serviços de saúde e à rede de proteção social.",
    "publico_principal": "Migrantes, refugiados e apátridas",
    "segundo_publico": "Profissionais de saúde e de assistência social",
    "outros_publicos": "",
    "nacionalidades": "Qualquer nacionalidade, com foco em migrantes e refugiados",
    "perfil_migratorio": "Migrantes internacionais / Refugiados",
    "servicos": "Capacitação profissional/ Apoio psicossocial , Saúde, Mediação cultural",
    "forma_acesso": "todas as formas citadas acima",
    "horarios": "8h00 - 18h, segunda - sexta e final de semana conforme a agenda dos colaboradores",
    "categorias": [
      "Saúde",
      "Apoio psicossocial",
      "Capacitação profissional"
    ],
    "nacionalidades_lista": [
      "Qualquer nacionalidade",
      "com foco em migrantes",
      "refugiados"
    ]
  },
  {
    "city": "Jacarezinho",
    "lat": -23.1597,
    "lng": -49.9739,
    "org": "CÁRITAS DIOCESANA DE JACAREZINHO",
    "responsavel": "LUAN KEVISON FERREIRA LOPES",
    "cnpj": "78.212.651/0001-32",
    "fundacao": "1966-05-13",
    "tempo_atuacao": "60 ANOS",
    "email": "caritasjacarezinho@gmail.com",
    "endereco": "Avenida Getúlio Vargas, 401, centro",
    "mais_de_uma_sede": "",
    "telefone": "4399617-9040",
    "site": "não temos",
    "redes_sociais": "@Caritasdiocesanadejacarezinho",
    "tipo_entidade": "OSC | ONG, Igreja | Iglesia",
    "areas_atuacao": "Assistência Social",
    "problema": "A organização busca enfrentar situações de pobreza, vulnerabilidade social, exclusão e violações de direitos, oferecendo acolhimento, orientação e apoio às pessoas que mais necessitam, especialmente migrantes, refugiados, pessoas em situação de rua e famílias em extrema vulnerabilidade. Existe para promover a dignidade humana, a solidariedade e o acesso a direitos, contribuindo para uma sociedade mais justa, inclusiva e fraterna.",
    "como_resolve": "A Cáritas Diocesana de Jacarezinho enfrenta essas situações por meio de acolhimento humanitário, atendimento social, orientação e encaminhamento para a rede de serviços públicos e comunitários. Desenvolve ações de apoio emergencial, como alimentos, roupas e itens de higiene, além de iniciativas de integração de migrantes e refugiados, acesso à documentação, educação, trabalho e direitos. Também promove ações de solidariedade, mobilização comunitária e articulação com outras instituições para fortalecer a autonomia e a dignidade das pessoas atendidas.",
    "atividades": "As principais atividades realizadas pela Cáritas Diocesana de Jacarezinho incluem acolhimento e atendimento social de pessoas em situação de vulnerabilidade, especialmente migrantes, refugiados, pessoas em situação de rua e famílias em extrema vulnerabilidade. A organização realiza orientação e apoio para regularização documental, acesso a direitos e serviços públicos, além de encaminhamentos para as áreas de saúde, educação, assistência social e trabalho.Também desenvolve ações de segurança alimentar e apoio emergencial, com distribuição de cestas básicas, alimentos, roupas, itens de higiene, fraldas e marmitas. Promove ainda ações de integração e inclusão social, como a Escola para Migrantes, atividades comunitárias, campanhas de solidariedade, formação de voluntários e articulação com a rede socioassistencial, órgãos públicos, paróquias e outras organizações.",
    "publico_principal": "O público principal atendido pela Cáritas Diocesana de Jacarezinho é composto por pessoas e famílias em situação de vulnerabilidade social e econômica, com atenção especial a **migrantes e refugiados, pessoas em situação de rua, famílias em extrema vulnerabilidade, crianças, idosos e pessoas que enfrentam dificuldades de acesso a direitos e serviços públicos**.",
    "segundo_publico": "Como segundo principal público, a organização atende pessoas em situação de rua e famílias em extrema vulnerabilidade social, que necessitam de apoio emergencial, orientação, encaminhamentos e acesso à rede de proteção social.",
    "outros_publicos": "Sim. Além dos públicos prioritários, a Cáritas Diocesana de Jacarezinho também atende **crianças, adolescentes, idosos, pessoas com deficiência, mulheres e famílias em situação de vulnerabilidade**, bem como pessoas que necessitam de apoio para acesso à documentação, serviços públicos, saúde, educação, trabalho e demais direitos sociais. A organização também envolve **voluntários, agentes pastorais e a comunidade local** em suas ações de solidariedade e promoção da cidadania.",
    "nacionalidades": "VENEZUELANO/BLAGLADESH/SUDÃO",
    "perfil_migratorio": "Refugiados | Refugiados",
    "servicos": "Regularização migratória - documentação | Regularización migratoria - documentación",
    "forma_acesso": "Atendimento Remoto | Atendimiento Online",
    "horarios": "TERÇA À QUINTA 9H-12H/ 13H30-16H30",
    "categorias": [
      "Assistência Social"
    ],
    "nacionalidades_lista": [
      "VENEZUELANO",
      "BLAGLADESH",
      "SUDÃO"
    ]
  },
  {
    "city": "Curitiba",
    "lat": -25.4284,
    "lng": -49.2733,
    "org": "Atuação Global",
    "responsavel": "Juliana Pompeo Helpa",
    "cnpj": "10.193.218.0001-63",
    "fundacao": "2008-04-27",
    "tempo_atuacao": "18 anos",
    "email": "contato@atuacaoglobal.org.br",
    "endereco": "Pedro Foggiatto, 530",
    "mais_de_uma_sede": "SIM / SI",
    "telefone": "41 999675416",
    "site": "www.atuacaoglobal.org.br",
    "redes_sociais": "https://www.instagram.com/atuacaoglobal/",
    "tipo_entidade": "OSC | ONG",
    "areas_atuacao": "Educação |  Educacíón",
    "problema": "Nossa missão é inspirar e servir profissionais, capacitando-os a realizar ações de prevenção, proteção e garantia dos direitos de crianças e adolescentes.",
    "como_resolve": "Desenvolvemos Programas e Projetos socio educativos para crianças e adoelscentes em contraturno escolar.",
    "atividades": "Nós existimos para inspirar e servir aos que servem às crianças. Por isso, criamos Programas Educacionais que ajudam a inspirar e capacitar pessoas a fazerem a diferença.",
    "publico_principal": "Crianças e adolescentes",
    "segundo_publico": "Educadores sociais",
    "outros_publicos": "Famílias",
    "nacionalidades": "Brasileiros e venezuelanos",
    "perfil_migratorio": "População brasileira em vulnerabilidade | Población brasileña en situación de vulnerabilidad",
    "servicos": "Educação | Educación",
    "forma_acesso": "O migrante vem até a organização (demanda espontânea) | El migrante llega directamente a la organización (demanda espontánea)",
    "horarios": "Segunda a sexta-feira das 9h às 17h",
    "categorias": [
      "Educação |  Educacíón"
    ],
    "nacionalidades_lista": [
      "Brasileiros",
      "venezuelanos"
    ]
  }
];

// Compatibilidade com versões do mapa que usam esses nomes.
const dadosInstituicoes = localizacoes;
